server:
  port: 5432
spring:
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://ec2-34-197-84-74.compute-1.amazonaws.com:5432/d2s516si419d71?socketTimeout=3
    username: rhqccxqeueqcgf
    password: 46e5a14c8267142f10b9604a082706b6f3e83764303955311bf6025b5b81925f
    driverClassName: org.postgresql.Driver
